// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCoreFiles() {
  return window['go']['main']['App']['GetCoreFiles']();
}

export function GetHyprpaperConfig() {
  return window['go']['main']['App']['GetHyprpaperConfig']();
}

export function UpdateHyprpaperWallpaper(arg1) {
  return window['go']['main']['App']['UpdateHyprpaperWallpaper'](arg1);
}
