// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfigFilesPath(): Promise<string>;

export function GetFileContent(arg1: string): Promise<string>;

export function GetSourcedFilePaths(): Promise<Array<string>>;

export function SaveFile(arg1: string, arg2: string): Promise<boolean>;
