// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfigFilesPath() {
    return window['go']['main']['App']['GetConfigFilesPath']();
}

export function GetFileContent(arg1) {
    return window['go']['main']['App']['GetFileContent'](arg1);
}

export function GetSourcedFilePaths() {
    return window['go']['main']['App']['GetSourcedFilePaths']();
}

export function SaveFile(arg1, arg2) {
    return window['go']['main']['App']['SaveFile'](arg1, arg2);
}
