// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {Core} from '../models';

export function GetCoreFiles():Promise<Array<Core.CoreFile>>;

export function GetHyprpaperConfig():Promise<string>;

export function UpdateHyprpaperWallpaper(arg1:string):Promise<void>;
